language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python -m app.tests

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJI3MT5MJU4USAM7A
  secret_access_key:
    secure: "MqtIYXCPYqVlye9D8PwykNlATenUtYwhDycqBzGu0VnYIa5CrDbRvNxoUK9RtSlqfaEKmpilczS0A563VecNh3i1nmDY1iKnkT6+3WZ95cDZ5W7TYwWqiXGwL+ih60TpGr0nZfHyLTCtHRiExLG5Iijnh192Dw8oZyiJsxsfX96/l55llPc356jxQkKpRralkdfB0lP2FHo04yEhmYsbYJU2FJtiDYE1rZYG7+HZKK9LYsNMk6Fj2ULETBHeT2hP2dlZK7heAa/Kb4CAMKsUq5293oJv/m9i5l1KUCx6Fim21UCBPphLYAUjMt9HX/oEke79j7R0nVKY7Pc9OJ0TaKA1zm5y4l9Y5sYTnTzDcD2qaZCBn5ZrlN25oAULik5WzQ4jver6SHh7AnbB2DuouWct7tsep+LsXargUMgh5pzO/hxhU6NdzDnBcnqdz4SveRxDvFjnMU0RK5r9/RK9lQ034L2zsMyT+GklX9sLzAEEMqTnXpyQV+TIjAjiafG++udOS6RNnLsh/foZ007lJSP25pm+oqCOL9F/eFLv2i8UvB1d8TxQpcjuBSu9R66JqMsAlWlXtZaq9rHPnMyVVeHR+VTXbCKi8Q4OJzo41k6Zf8jt4dH7M5wragFBShpzjLRg1oTFrqxUZkemSWjzdwec8LmDHp57+uj2aMNDwOw="
  region: "us-west-2"  
  app: "project"
  env: "swe16project"
  bucket_name: "elasticbeanstalk-us-west-2-536572426247"