language: python
python:
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python -m app.tests

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAJI3MT5MJU4USAM7A
  secret_access_key:
    secure: "6JF6S4W9/oJuHSkSgYEW7Fxjib+RCuDs/HVIZ+m0ObpnNOaUhQGQFsLM8gFIv/RT8DhejJaOkMD406Aqr3bzIcU5n5wB10Lx/m+T6Bk8UK3zSRClPJXuI90silaaLK9k5a/sGR3xhl5OzB7j7QezHVjjaDjxTt2fGP6X3lx7Dqu5ssyuhMCnG+P4jhyBsE0DUxYgaoDEiRNoFYl2W9hZQO8hTy9zfQVeN8K22JKZsHwyv2REpValwPj+nDSmCWk9IMNQZc0hz0M5LDIWcznQud6bhOas4dFc+evunO0Oq0RqUz5Tx7Fbkqkbkx0kERotBRIwBpMsTrOECX6ncuyAyHbtaVSI9FNH6Y2H8MXJvx4kIbxozPQD5DzevAlxjpy39mPsCU3sbq/Ux/3JqHHrDxxNojojeQDwG3q3xxNPWrkPDxy6K4IVXFONorI6redOhckHVd55lyhAtasdZKQb/SQKbee4bkZ9cWeZdD98IeUxpg99PqiGXn27Y7HyYjc3r587KnEnTpE3UpDqwSplj03Kr+xAOK8+1BD+sGBU8MddoT+DQBA9l+68uix3e6qfiaASDGBREGF7hMnscTbHr9tTW/GeDduBvcPUFa7mJ60eiKQy3UoYJfecoNRT4+08G80uluCT+wY1VYMeHkum7xEgeql/2DPzhUNk4Bt0DdM="
  region: "us-west-2"  
  app: "project"
  env: "swe16project"
  bucket_name: "elasticbeanstalk-us-west-2-536572426247"