FORMAT: 1A
HOST: http://gotthrones.me/api/

# gottrones

Api to navigate the wonderful world of Westeros

## Character Page [/characters?{page}&{sortParam}&{sortAscending}&{filter}]

### Gets information for a page of Characters [GET]
Gets the characters to display on a certain page of the application

+ Parameters
    + page (number, `page=1`) ... Page number of the characters
    + sortParam (optional, string, `sortParam=Name`) ... Parameter you are sorting by; can be Name, House, Culture, Gender
    + sortAscending (optional, number, `sortAscending=1`) ... Whether to sort by ascending
    + filter (optional, string, `filter=Varys`) ... Word to filter by
    
    
+ Response 200 (application/json)

        {
            "pageData": 
            {
                "currentPage": 1, 
                "numberPages": 1
            }, 
            "cardData": 
            [
                {
                    "cardURL": "/characters", 
                    "cardName": "Varys", 
                    "cardID": 2069
                }
            ]
        }

## Book Page [/books?{page}&{sortParam}&{sortAscending}&{filter}]

### Gets information for a page of Books [GET]
Gets the books to display on a certain page of the application

+ Parameters
    + page (number, `page=1`) ... Page number of the books
    + sortParam (optional, string, `sortParam=Name`) ... Parameter you are sorting by; can be Name, Author, Publisher, ISBN, Number%20of%20Pages, Release%20Date
    + sortAscending (optional, number, `sortAscending=1`) ... Whether to sort by ascending
    + filter (optional, string, `filter=Clash`) ... Word to filter by
    
    
+ Response 200 (application/json)

        {
            "pageData": 
            {
                "currentPage": 1, 
                "numberPages": 1
            }, 
            "cardData": 
            [
                {
                    "cardURL": "/books", 
                    "cardName": "A Clash of Kings", 
                    "cardID": 2
                }
            ]
        }
        
## House Page [/houses?{page}&{sortParam}&{sortAscending}&{filter}]

### Gets information for a page of Houses [GET]
Gets the houses to display on a certain page of the application

+ Parameters
    + page (number, `page=1`) ... Page number of the houses
    + sortParam (optional, string, `sortParam=Name`) ... Parameter you are sorting by; can be Name, Region, Coat%20of%20Arms, Words
    + sortAscending (optional, number, `sortAscending=1`) ... Whether to sort by ascending
    + filter (optional, string, `filter=Stark`) ... Word to filter by
    
    
+ Response 200 (application/json)

        {
            "pageData": 
            {
                "currentPage": 1, 
                "numberPages": 1
            }, 
            "cardData": 
            [
                [
                    {
                        "cardURL": "/houses", 
                        "cardName": "House Stark of Winterfell", 
                        "cardID": 362
                    }
                ]
            ]
        }
        
## Alliance Page [/alliances?{page}&{sortParam}&{sortAscending}&{filter}]

### Gets information for a page of Alliances [GET]
Gets the alliances to display on a certain page of the application

+ Parameters
    + page (number, `page=1`) ... Page number of the alliances
    + sortParam (optional, string, `sortParam=Name`) ... Parameter you are sorting by; can be Name, Current%20Head%20House, Number%of%20Members
    + sortAscending (optional, number, `sortAscending=1`) ... Whether to sort by ascending
    + filter (optional, string, `filter=ruler`) ... Word to filter by
    
    
+ Response 200 (application/json)

        {
            "pageData": 
            {
                "currentPage": 1, 
                "numberPages": 1
            }, 
            "cardData": 
            [
                {
                    "cardURL": "/alliances", 
                    "cardName": "The Rightful Ruler of the Seven Kingdoms", 
                    "cardID": 3
                }
            ]
        }