branch-defaults:
  default:
    environment: flask-env
    group_suffix: null
global:
  application_name: flask-tutorial
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python3.4
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
